### PR TITLE
Convert ISA-JSON to ENA Analysis XML

### PR DESCRIPTION
**Pull request by apriltuesday**

### CODE REVIEW

**Comment by yvanlebras** [comment]
Hi. Just see there is work on ISA during Biohackahton, and as I am interested to create a mapping and conversion script between ISA and EML (Ecological Metadata Language) if there is somewhere I can contribute to start this, please don't hesitate to say to me ;)

**Comment by yvanlebras** [comment]
I ping @proccaserra  as it is something we discussed during GO FAIR meetings ;)

**Comment by apriltuesday** [comment]
Hi, sorry I did not get back to you earlier, it's been busy today! [This project](https://github.com/elixir-europe/biohackathon-projects-2023/tree/main/27) is about converting ISA-JSON to different data repository submission formats for streamlining multi-omics submissions, but of course we are happy to talk about or help with conversion more generally (and if it can fit into the submissions framework we're definitely very interested)

**Comment by apriltuesday** [comment]
Yes, let me quickly resolve merge conflicts right now and I will merge.

**Comment by proccaserra** [comment]
@yvanlebras let's follow up and document the context and use case. Thank you for reaching out!

**Pull request merged**
